[project]
name = "honest-llama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "datasets>=3.1.0",
    "einops>=0.8.1",
    "scikit-learn>=1.3.2",
    "torch>=2.5.1",
    "transformers>=4.46.3",
]
